### ISSUE TITLE
order 5 or 6 esp8266 dev boards

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/gardenmesh#9]

**Comment by paidforby** [comment]
ESP8266 - https://www.amazon.com/Makerfocus-NodeMcu-Development-ESP8266-ESP-12F/dp/B01N3P763C/ref=sr_1_2?ie=UTF8&qid=1499834516&sr=8-2&keywords=wemos+d1+mini

**Comment by jhpoelen** [comment]
also see components wiki - https://github.com/sudomesh/gardenmesh/wiki#components

**Comment by paidforby** [comment]
18650 charging circuit https://www.amazon.com/XCSOURCE-Lithium-Battery-Charger-TE585/dp/B01LZSC7I8/ref=sr_1_2?ie=UTF8&qid=1499837830&sr=8-2&keywords=TP4056

**Comment by Mgabiati** [comment]
Hi guys, here is the shopping list I will order this afternoon:

https://www.amazon.com/gp/aw/c/ref=navm_hdr_cart

The soil moisture sensors are still the most expensive part - should I order from DF Robot directly  considering they are $13ea on Amazon, or bite the bullet because we need them asap? I found a few digital soil moisture sensors we can try out as well, they are in the cart and I intend to order them anyway to try out. 

Let me know if I left anything else out. Cheers, 

-Mario

**Comment by paidforby** [comment]
Can you send a screenshot, that link redirects to my Amazon cart. (is it
possible to create a public Amazon cart?)
-grant

**Comment by Mgabiati** [comment]
Hey guys, bringing everything that was delivered to the meeting tonight so we can figure out what else we might need. Probably going to arrive around 8p

**Comment by paidforby** [comment]
Here's a 4 pack of 18650s
https://www.amazon.com/NCR18650B-Rechargeable-Panasonic-Carrying-Transport/dp/B01HOWL44M/ref=sr_1_2?ie=UTF8&qid=1500498386&sr=8-2&keywords=panasonic+18650

and a 10 pack of their corresponding holders,
https://www.amazon.com/yueton-Battery-Storage-Holder-Button/dp/B013DUOJV4/ref=sr_1_4?ie=UTF8&qid=1500498419&sr=8-4&keywords=18650+battery+holder

**Comment by Mgabiati** [comment]
Hey guys, I'm going to close this thread and start a new equipment list thread. Cheers.
